name: Update Profile Projects

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Python projelerini al
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

          curl -s https://api.github.com/users/diclebilgisayar/repos \
          | jq -r '.[] 
            | select(.language=="Python") 
            | select(.fork==false) 
            | "- üßÆ **[" + .name + "](" + .html_url + ")**"' \
          > projects.txt

          echo "---- PROJECTS.TXT ----"
          cat projects.txt

      - name: Marker kontrol√º
        run: |
          grep "<!-- PROJECTS:START -->" README.md
          grep "<!-- PROJECTS:END -->" README.md

      - name: README.md g√ºncelle
        run: |
          sed -i '/<!-- PROJECTS:START -->/,/<!-- PROJECTS:END -->/{
          /<!-- PROJECTS:START -->/!{/<!-- PROJECTS:END -->/!d;}
          }' README.md

          sed -i '/<!-- PROJECTS:START -->/r projects.txt' README.md

      - name: Commit et
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          if ! git diff --quiet; then
            git add README.md
            git commit -m "Update projects list"
            git push
          else
            echo "README deƒüi≈ümedi"
          fi
